apiVersion: v1
kind: Pod
metadata: 
  name: pod-cilium
  labels: 
    app: benchmarking-app
spec: 
  containers:
    - name: l7fw-app
      image: lehuannhatrang/l7fw-app:latest
      ports:
        - protocol: TCP
          containerPort: 8080
        - protocol: TCP
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: cilium-nodeport
spec:
  type: NodePort
  selector:
    app: benchmarking-app
  ports:
    - port: 8080
      targetPort: 8080 
      nodePort: 30080
      protocol: TCP
      name: tcp-port-1
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
      name: tcp-port-2